export const forestsInfo = [
    {
        id: 1,
        topic: 'Forests',
        text: `A forest is an ecosystem characterized by a dense community of trees.[2] Hundreds of definitions of forest are used throughout the world, incorporating factors such as tree density, tree height, land use, legal standing, and ecological function.[3][4][5] The United Nations' Food and Agriculture Organization (FAO) defines a forest as, "Land spanning more than 0.5 hectares with trees higher than 5 meters and a canopy cover of more than 10 percent, or trees able to reach these thresholds in situ. It does not include land that is predominantly under agricultural or urban use."[6] Using this definition, Global Forest Resources Assessment 2020 found that forests covered 4.06 billion hectares (10.0 billion acres; 40.6 million square kilometres; 15.7 million square miles), or approximately 31 percent of the world's land area in 2020.[7]
                Forests are the largest terrestrial ecosystems of Earth by area, and are found around the globe.[8] 45 percent of forest land is in the tropical latitudes. The next largest share of forests are found in subarctic climates, followed by temperate, and subtropical zones.[9]
                Forests account for 75% of the gross primary production of the Earth's biosphere, and contain 80% of the Earth's plant biomass. Net primary production is estimated at 21.9 gigatonnes of biomass per year for tropical forests, 8.1 for temperate forests, and 2.6 for boreal forests.[8]
                Forests form distinctly different biomes at different latitudes and elevations, and with different precipitation and evapotranspiration rates.[10] These biomes include boreal forests in subarctic climates, tropical moist forests and tropical dry forests around the Equator, and temperate forests at the middle latitudes. Forests form in areas of the Earth with high rainfall, while drier conditions produce a transition to savanna. However, in areas with intermediate rainfall levels, forest transitions to savanna rapidly when the percentage of land that is covered by trees drops below 40 to 45 percent.[11] Research conducted in the Amazon rainforest shows that trees can alter rainfall rates across a region, releasing water from their leaves in anticipation of seasonal rains to trigger the wet season early. Because of this, seasonal rainfall in the Amazon begins two to three months earlier than the climate would otherwise allow.[12][13] Deforestation in the Amazon and anthropogenic climate change hold the potential to interfere with this process, causing the forest to pass a threshold where it transitions into savanna.[14]
                Deforestation threatens many forest ecosystems. Deforestation occurs when humans remove trees from a forested area by cutting or burning, either to harvest timber or to make way for farming. Most deforestation today occurs in tropical forests. The vast majority of this deforestation is because of the production of four commodities: wood, beef, soy, and palm oil.[15] Over the past 2,000 years, the area of land covered by forest in Europe has been reduced from 80% to 34%. Large areas of forest have also been cleared in China and in the eastern United States,[16] in which only 0.1% of land was left undisturbed.[17] Almost half of Earth's forest area (49 percent) is relatively intact, while 9 percent is found in fragments with little or no connectivity. Tropical rainforests and boreal coniferous forests are the least fragmented, whereas subtropical dry forests and temperate oceanic forests are among the most fragmented. Roughly 80 percent of the world's forest area is found in patches larger than 1 million hectares (2.5 million acres). The remaining 20 percent is located in more than 34 million patches around the world – the vast majority less than 1,000 hectares (2,500 acres) in size.[9]
                Human society and forests can affect one another positively or negatively.[18] Forests provide ecosystem services to humans and serve as tourist attractions. Forests can also affect people's health. Human activities, including unsustainable use of forest resources, can negatively affect forest ecosystems.[19]`
    },
    {
        id: 2,
        topic: 'Definitions',
        text: `Although the word forest is commonly used, there is no universally recognised precise definition, with more than 800 definitions of forest used around the world.[5] Although a forest is usually defined by the presence of trees, under many definitions an area completely lacking trees may still be considered a forest if it grew trees in the past, will grow trees in the future,[20] or was legally designated as a forest regardless of vegetation type.[21][22]
                There are three broad categories of definitions of forest in use: administrative, land use, and land cover.[21] Administrative definitions are legal designations, and may not reflect the type of vegetation that grows upon the land; an area can be legally designated "forest" even if no trees grow on it.[21] Land-use definitions are based on the primary purpose the land is used for. Under a land-use definition, any area used primarily for harvesting timber, including areas that have been cleared by harvesting, disease, fire, or for the construction of roads and infrastructure, are still defined as forests, even if they contain no trees. Land-cover definitions define forests based upon the density of trees, area of tree canopy cover, or area of the land occupied by the cross-section of tree trunks (basal area) meeting a particular threshold.[21] This type of definition depends upon the presence of trees sufficient to meet the threshold, or at least of immature trees that are expected to meet the threshold once they mature.[21]
                Under land-cover definitions, there is considerable variation on where the cutoff points are between a forest, woodland, and savanna. Under some definitions, to be considered a forest requires very high levels of tree canopy cover, from 60% to 100%,[23] which excludes woodlands and savannas, which have a lower canopy cover. Other definitions consider savannas to be a type of forest, and include all areas with tree canopies over 10%.[20]
                Some areas covered with trees are legally defined as agricultural areas, for example Norway spruce plantations, under Austrian forest law, when the trees are being grown as Christmas trees and are below a certain height.`
    },
    {
        id: 3,
        topic: 'Etymology',
        text: `The word forest derives from the Old French forest (also forès), denoting "forest, vast expanse covered by trees"; forest was first introduced into English as the word denoting wild land set aside for hunting[25] without necessarily having trees on the land.[26] Possibly a borrowing, probably via Frankish or Old High German, of the Medieval Latin foresta, denoting "open wood", Carolingian scribes first used foresta in the capitularies of Charlemagne, specifically to denote the royal hunting grounds of the king. The word was not endemic to the Romance languages, e.g., native words for forest in the Romance languages derived from the Latin silva, which denoted "forest" and "wood(land)" (cf. the English sylva and sylvan; the Italian, Spanish, and Portuguese selva; the Romanian silvă; the Old French selve). Cognates of forest in Romance languages—e.g., the Italian foresta, Spanish and Portuguese floresta, etc.—are all ultimately derivations of the French word.
                The precise origin of Medieval Latin foresta is obscure. Some authorities claim the word derives from the Late Latin phrase forestam silvam, denoting "the outer wood"; others claim the word is a Latinisation of the Frankish *forhist, denoting "forest, wooded country", and was assimilated to forestam silvam, pursuant to the common practice of Frankish scribes. The Old High German forst denoting "forest"; Middle Low German vorst denoting "forest"; Old English fyrhþ denoting "forest, woodland, game preserve, hunting ground" (English frith); and Old Norse fýri, denoting "coniferous forest"; all of which derive from the Proto-Germanic *furhísa-, *furhíþija-, denoting "a fir-wood, coniferous forest", from the Proto-Indo-European *perkwu-, denoting "a coniferous or mountain forest, wooded height" all attest to the Frankish *forhist.
                Uses of forest in English to denote any uninhabited and unenclosed area are presently considered archaic.[27] The Norman rulers of England introduced the word as a legal term, as seen in Latin texts such as Magna Carta, to denote uncultivated land that was legally designated for hunting by feudal nobility (see royal forest).[27][28]
                These hunting forests did not necessarily contain any trees. Because that often included significant areas of woodland, "forest" eventually came to connote woodland in general, regardless of tree density.[citation needed] By the beginning of the fourteenth century, English texts used the word in all three of its senses: common, legal, and archaic.[27] Other English words used to denote "an area with a high density of trees" are firth, frith, holt, weald, wold, wood, and woodland. Unlike forest, these are all derived from Old English and were not borrowed from another language. Some present classifications reserve woodland for denoting a locale with more open space between trees, and distinguish kinds of woodlands as open forests and closed forests, premised on their crown covers.[29] Finally, sylva (plural sylvae or, less classically, sylvas) is a peculiar English spelling of the Latin silva, denoting a "woodland", and has precedent in English, including its plural forms. 
                While its use as a synonym of forest, and as a Latinate word denoting a woodland, may be admitted; in a specific technical sense it is restricted to denoting the species of trees that comprise the woodlands of a region, as in its sense in the subject of silviculture.[30] The resorting to sylva in English indicates more precisely the denotation that the use of forest intends.`
    },
    {
        id: 4,
        topic: 'Ecology',
        text: `Forests account for 75% of the gross primary productivity of the Earth's biosphere, and contain 80% of the Earth's plant biomass.[8] Biomass per unit area is high compared to other vegetation communities. Much of this biomass occurs below ground in the root systems and as partially decomposed plant detritus. The woody component of a forest contains lignin, which is relatively slow to decompose compared with other organic materials such as cellulose or carbohydrate. The world's forests contain about 606 gigatonnes of living biomass (above- and below-ground) and 59 gigatonnes of dead wood. The total biomass has decreased slightly since 1990, but biomass per unit area has increased.[33]
                Forest ecosystems broadly differ based on climate; latitudes 10° north and south of the equator are mostly covered in tropical rainforest, and the latitudes between 53°N and 67°N have boreal forest. As a general rule, forests dominated by angiosperms (broadleaf forests) are more species-rich than those dominated by gymnosperms (conifer, montane, or needleleaf forests), although exceptions exist. The trees that form the principal structural and defining component of a forest may be of a great variety of species (as in tropical rainforests and temperate deciduous forests), or relatively few species over large areas (e.g., taiga and arid montane coniferous forests). The biodiversity of forests also encompasses shrubs, herbaceous plants, mosses, ferns, lichens, fungi, and a variety of animals.
                Trees rising up to 35 meters (115 ft) in height add a vertical dimension to the area of land that can support plant and animal species, opening up numerous ecological niches for arboreal animal species, epiphytes, and various species that thrive under the regulated microclimate created under the canopy.[34] Forests have intricate three-dimensional structures that increase in complexity with lower levels of disturbance and greater variety of tree species.[35]
                The biodiversity of forests varies considerably according to factors such as forest type, geography, climate, and soils – in addition to human use.[36] Most forest habitats in temperate regions support relatively few animal and plant species, and species that tend to have large geographical distributions, while the montane forests of Africa, South America, Southeast Asia, and lowland forests of Australia, coastal Brazil, the Caribbean islands, Central America, and insular Southeast Asia have many species with small geographical distributions.[36] Areas with dense human populations and intense agricultural land use, such as Europe, parts of Bangladesh, China, India, and North America, are less intact in terms of their biodiversity.[36] Northern Africa, southern Australia, coastal Brazil, Madagascar, and South Africa are also identified as areas with striking losses in biodiversity intactness.`
    },
    {
        id: 5,
        topic: 'Layers',
        text: `The main layers of all forest types are the forest floor, the understory, and the canopy. The emergent layer, above the canopy, exists in tropical rainforests. Each layer has a different set of plants and animals, depending upon the availability of sunlight, moisture, and food.
                The Forest floor is covered in dead plant material such as fallen leaves and decomposing logs, which detritivores break down into new soil. The layer of decaying leaves that covers the soil is necessary for many insects to overwinter and for amphibians, birds, and other animals to shelter and forage for food. Leaf litter also keeps the soil moist, stops erosion, and protects roots against extreme heat and cold.[38] The fungal mycelium that helps form the mycorrhizal network transmits nutrients from decaying material to trees and other plants. The forest floor supports a variety of plants, ferns, grasses, and tree seedlings, as well as animals such as ants, amphibians, spiders, and millipedes.
                Understory is made up of bushes, shrubs, and young trees that are adapted to living in the shade of the canopy.
                Canopy is formed by the mass of intertwined branches, twigs, and leaves of mature trees. The crowns of the dominant trees receive most of the sunlight. This is the most productive part of the trees, where maximum food is produced. The canopy forms a shady, protective "umbrella" over the rest of the forest.
                Emergent layer exists in a tropical rain forest and is composed of a few scattered trees that tower over the canopy.[39]
                In botany and countries like Germany and Poland, a different classification of forest vegetation is often used: tree, shrub, herb, and moss layers (see stratification (vegetation)).`
    },
    {
        id: 6,
        topic: 'Types',
        text: `Forests are classified differently and to different degrees of specificity. One such classification is in terms of the biomes in which they exist, combined with leaf longevity of the dominant species (whether they are evergreen or deciduous). Another distinction is whether the forests are composed predominantly of broadleaf trees, coniferous (needle-leaved) trees, or mixed.
                Boreal forests occupy the subarctic zone and are generally evergreen and coniferous.
                Temperate zones support both broadleaf deciduous forests (e.g., temperate deciduous forest) and evergreen coniferous forests (e.g., temperate coniferous forests and temperate rainforests). Warm temperate zones support broadleaf evergreen forests, including laurel forests.
                Tropical and subtropical forests include tropical and subtropical moist forests, tropical and subtropical dry forests, and tropical and subtropical coniferous forests.
                Forests are classified according to physiognomy based on their overall physical structure or developmental stage (e.g. old growth vs. second growth).
                Forests can also be classified more specifically based on the climate and the dominant tree species present, resulting in numerous different forest types (e.g., Ponderosa pine/Douglas fir forest).
                The number of trees in the world, according to a 2015 estimate, is 3 trillion, of which 1.4 trillion are in the tropics or sub-tropics, 0.6 trillion in the temperate zones, and 0.7 trillion in the coniferous boreal forests. The 2015 estimate is about eight times higher than previous estimates, and is based on tree densities measured on over 400,000 plots. It remains subject to a wide margin of error, not least because the samples are mainly from Europe and North America.[40]
                Forests can also be classified according to the amount of human alteration. Old-growth forest contains mainly natural patterns of biodiversity in established seral patterns, and they contain mainly species native to the region and habitat. In contrast, secondary forest is forest regrowing following timber harvest and may contain species originally from other regions or habitats.[41]
                Different global forest classification systems have been proposed, but none has gained universal acceptance.[42] UNEP-WCMC's forest category classification system is a simplification of other, more complex systems (e.g. UNESCO's forest and woodland 'subformations'). This system divides the world's forests into 26 major types, which reflect climatic zones as well as the principal types of trees. These 26 major types can be reclassified into 6 broader categories: temperate needleleaf, temperate broadleaf and mixed, tropical moist, tropical dry, sparse trees and parkland, and forest plantations.[42] Each category is described in a separate section below.`,
        children: [
            {
                id: 601,
                topic: 'Temperate needleleaf',
                text: `Temperate needleleaf forests mostly occupy the higher latitudes of the Northern Hemisphere, as well as some warm temperate areas, especially on nutrient-poor or otherwise unfavourable soils. These forests are composed entirely, or nearly so, of coniferous species (Coniferophyta). In the Northern Hemisphere, pines Pinus, spruces Picea, larches Larix, firs Abies, Douglas firs Pseudotsuga, and hemlocks Tsuga make up the canopy; but other taxa are also important. In the Southern Hemisphere, most coniferous trees (members of Araucariaceae and Podocarpaceae) occur mixed with broadleaf species, and are classed as broadleaf-and-mixed forests.`
            },
            {
                id: 602,
                topic: 'Temperate broadleaf and mixed',
                text: `Temperate broadleaf and mixed forests include a substantial component of trees of the Anthophyta group. They are generally characteristic of the warmer temperate latitudes, but extend to cool temperate ones, particularly in the southern hemisphere. They include such forest types as the mixed deciduous forests of the United States and their counterparts in China and Japan; the broadleaf evergreen rainforests of Japan, Chile, and Tasmania; the sclerophyllous forests of Australia, central Chile, the Mediterranean, and California; and the southern beech Nothofagus forests of Chile and New Zealand.`
            },
            {
                id: 603,
                topic: 'Tropical moist',
                text: `There are many different types of tropical moist forests, with lowland evergreen broad-leaf tropical rainforests: for example várzea and igapó forests and the terra firme forests of the Amazon Basin; the peat swamp forests; dipterocarp forests of Southeast Asia; and the high forests of the Congo Basin. Seasonal tropical forests, perhaps the best description for the colloquial term "jungle", typically range from the rainforest zone 10 degrees north or south of the equator, to the Tropic of Cancer and Tropic of Capricorn. Forests located on mountains are also included in this category, divided largely into upper and lower montane formations, on the basis of the variation of physiognomy corresponding to changes in altitude.`
            },
            {
                id: 604,
                topic: 'Tropical dry',
                text: `Tropical dry forests are characteristic of areas in the tropics affected by seasonal drought. The seasonality of rainfall is usually reflected in the deciduousness of the forest canopy, with most trees being leafless for several months of the year. Under some conditions, such as less fertile soils or less predictable drought regimes, the proportion of evergreen species increases and the forests are characterised as "sclerophyllous". Thorn forest, a dense forest of low stature with a high frequency of thorny or spiny species, is found where drought is prolonged, and especially where grazing animals are plentiful. On very poor soils, and especially where fire or herbivory are recurrent phenomena, savannas develop.`
            },
            {
                id: 605,
                topic: 'Sparse trees and savanna',
                text: `Sparse trees and savanna are forests with sparse tree-canopy cover. They occur principally in areas of transition from forested to non-forested landscapes. The two major zones in which these ecosystems occur are in the boreal region and in the seasonally dry tropics. At high latitudes, north of the main zone of boreal forestland, growing conditions are not adequate to maintain a continuously closed forest cover, so tree cover is both sparse and discontinuous. This vegetation is variously called open taiga, open lichen woodland, and forest tundra. A savanna is a mixed woodland–grassland ecosystem characterized by the trees being sufficiently widely spaced so that the canopy does not close. The open canopy allows sufficient light to reach the ground to support an unbroken herbaceous layer that consists primarily of grasses. Savannas maintain an open canopy despite a high tree density.`
            },
            {
                id: 606,
                topic: 'Plantations',
                text: `Forest plantations are generally intended for the production of timber and pulpwood. Commonly mono-specific, planted with even spacing between the trees, and intensively managed, these forests are generally important as habitat for native biodiversity. Some are managed in ways that enhance their biodiversity protection functions and can provide ecosystem services such as nutrient capital maintenance, watershed and soil structure protection and carbon storage.`
            }
        ]
    },
    {
        id: 7,
        topic: 'Area',
        text: `The annual net loss of forest area has decreased since 1990, but the world is not on track to meet the target of the United Nations Strategic Plan for Forests to increase forest area by 3 percent by 2030.[36]
                Share of forest area in total land area, top countries (2021)
                While deforestation is taking place in some areas, new forests are being established through natural expansion or deliberate efforts in other areas. As a result, the net loss of forest area is less than the rate of deforestation; and it, too, is decreasing: from 7.8 million hectares (19 million acres) per year in the 1990s to 4.7 million hectares (12 million acres) per year during 2010–2020.[36] In absolute terms, the global forest area decreased by 178 million hectares (440 million acres; 1,780,000 square kilometres; 690,000 square miles) between 1990 and 2020, which is an area about the size of Libya.`
    }

]